version: '3.1'

services:

  db:
    image: postgres:9.6.3
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/acidb
      POSTGRES_DB: acidb
      POSTGRES_USER: aci-user
      POSTGRES_PASSWORD: aci-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080