SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS SA SALT 'be4d66d2c00ab2de' HASH '26bbfb5b8b8d5950721d78157b4babfa2311c24bd1022bb98e01f8d0d1997cce' ADMIN;            
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_64DCE0F3_DD53_48F2_823A_48A190F11173 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A4E2E39D_7539_478F_8AEA_F8C18FC906DC START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4489A331_D627_46AC_BD5C_F2B0A9F40CD9 START WITH 1 BELONGS_TO_TABLE;     
CREATE MEMORY TABLE PUBLIC.ACCORDION_ELEMENT(
    VIEW_ELEMENT_ID BIGINT NOT NULL
);           
ALTER TABLE PUBLIC.ACCORDION_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(VIEW_ELEMENT_ID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCORDION_ELEMENT;        
CREATE MEMORY TABLE PUBLIC.ELEMENT_LINKS(
    ID BIGINT NOT NULL,
    ELEMENT_ID BIGINT,
    PARENT_ELEMENT_ID BIGINT,
    VIEW_FRAGMENT_ENTITY_ID BIGINT
);   
ALTER TABLE PUBLIC.ELEMENT_LINKS ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ELEMENT_LINKS;            
CREATE MEMORY TABLE PUBLIC.FIELD_ELEMENT(
    VIEW_ELEMENT_ID BIGINT NOT NULL,
    FIELD_TYPE INTEGER,
    WIDTH VARCHAR(255)
);               
ALTER TABLE PUBLIC.FIELD_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_C7 PRIMARY KEY(VIEW_ELEMENT_ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FIELD_ELEMENT;            
CREATE MEMORY TABLE PUBLIC.GRID_ELEMENT(
    VIEW_ELEMENT_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.GRID_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(VIEW_ELEMENT_ID);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GRID_ELEMENT;             
CREATE MEMORY TABLE PUBLIC.OVERRIDE_ELEMENT(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_64DCE0F3_DD53_48F2_823A_48A190F11173) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_64DCE0F3_DD53_48F2_823A_48A190F11173,
    ELEMENT_ID BIGINT NOT NULL,
    ELEMENT_TYPE INTEGER,
    OVERRIDE_TYPE INTEGER
);          
ALTER TABLE PUBLIC.OVERRIDE_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OVERRIDE_ELEMENT;         
CREATE MEMORY TABLE PUBLIC.OVERRIDE_ELEMENT_VALUE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4489A331_D627_46AC_BD5C_F2B0A9F40CD9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4489A331_D627_46AC_BD5C_F2B0A9F40CD9,
    PROPERTY VARCHAR(255),
    VALUE VARCHAR(255),
    OVERRIDE_ELEMENT_ID BIGINT
);      
ALTER TABLE PUBLIC.OVERRIDE_ELEMENT_VALUE ADD CONSTRAINT PUBLIC.CONSTRAINT_C6 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OVERRIDE_ELEMENT_VALUE;   
CREATE MEMORY TABLE PUBLIC.PANEL_ELEMENT(
    VIEW_ELEMENT_ID BIGINT NOT NULL
);               
ALTER TABLE PUBLIC.PANEL_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(VIEW_ELEMENT_ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PANEL_ELEMENT;            
CREATE MEMORY TABLE PUBLIC.TAB_ELEMENT(
    VIEW_ELEMENT_ID BIGINT NOT NULL
); 
ALTER TABLE PUBLIC.TAB_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(VIEW_ELEMENT_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAB_ELEMENT;              
CREATE MEMORY TABLE PUBLIC.VIEW_ELEMENT(
    ID BIGINT NOT NULL,
    ANGULAR_COMPONENT_NAME VARCHAR(255),
    ELEMENT_ORDER BIGINT NOT NULL,
    ELEMENT_TYPE VARCHAR(255),
    LABEL_TRANSLATION_KEY VARCHAR(255),
    LAYOUT_TYPE VARCHAR(255),
    METADATA_DRIVEN BOOLEAN NOT NULL,
    NAME VARCHAR(255),
    VISIBLE BOOLEAN NOT NULL,
    VIEW_FRAGMENT_ID BIGINT
);    
ALTER TABLE PUBLIC.VIEW_ELEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VIEW_ELEMENT;             
CREATE MEMORY TABLE PUBLIC.VIEW_FRAGMENT(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A4E2E39D_7539_478F_8AEA_F8C18FC906DC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A4E2E39D_7539_478F_8AEA_F8C18FC906DC,
    LAYOUT_TYPE INTEGER,
    NAME VARCHAR(255)
);  
ALTER TABLE PUBLIC.VIEW_FRAGMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VIEW_FRAGMENT;            
ALTER TABLE PUBLIC.FIELD_ELEMENT ADD CONSTRAINT PUBLIC.FKI0LBO1RX7B1I1L4UCGWBX7NX0 FOREIGN KEY(VIEW_ELEMENT_ID) REFERENCES PUBLIC.VIEW_ELEMENT(ID) NOCHECK;    
ALTER TABLE PUBLIC.OVERRIDE_ELEMENT_VALUE ADD CONSTRAINT PUBLIC.FK4HIY4INGGVTINX4G0K7BSX3JO FOREIGN KEY(OVERRIDE_ELEMENT_ID) REFERENCES PUBLIC.OVERRIDE_ELEMENT(ID) NOCHECK;   
ALTER TABLE PUBLIC.TAB_ELEMENT ADD CONSTRAINT PUBLIC.FKLBG9O1XIVE65HJEPYKWP1ICS2 FOREIGN KEY(VIEW_ELEMENT_ID) REFERENCES PUBLIC.VIEW_ELEMENT(ID) NOCHECK;      
ALTER TABLE PUBLIC.ELEMENT_LINKS ADD CONSTRAINT PUBLIC.FK4KDGO7OKI9BNJ52EMMAWJJO7I FOREIGN KEY(VIEW_FRAGMENT_ENTITY_ID) REFERENCES PUBLIC.VIEW_FRAGMENT(ID) NOCHECK;           
ALTER TABLE PUBLIC.GRID_ELEMENT ADD CONSTRAINT PUBLIC.FK3S6I7J2JH4327EUFYEPI29KDE FOREIGN KEY(VIEW_ELEMENT_ID) REFERENCES PUBLIC.VIEW_ELEMENT(ID) NOCHECK;     
ALTER TABLE PUBLIC.VIEW_ELEMENT ADD CONSTRAINT PUBLIC.FKC2IE689CJUAF3PTJNQB2WDIRP FOREIGN KEY(VIEW_FRAGMENT_ID) REFERENCES PUBLIC.VIEW_FRAGMENT(ID) NOCHECK;   
ALTER TABLE PUBLIC.PANEL_ELEMENT ADD CONSTRAINT PUBLIC.FKQSV60CS768CBGINRYXG1YCBOR FOREIGN KEY(VIEW_ELEMENT_ID) REFERENCES PUBLIC.VIEW_ELEMENT(ID) NOCHECK;    
ALTER TABLE PUBLIC.ACCORDION_ELEMENT ADD CONSTRAINT PUBLIC.FKMWHLAS7MQ81CN6EXN779JTLTD FOREIGN KEY(VIEW_ELEMENT_ID) REFERENCES PUBLIC.VIEW_ELEMENT(ID) NOCHECK;
